/**
 * Единый источник иконок категорий для приложения.
 * Названия соответствуют Material Icons (fontIcon).
 * Эти же значения хранятся в БД в поле categories.icon.
 */
export const DEFAULT_CATEGORY_ICON = 'category';

export interface CategoryIconOption {
  value: string;
  label: string;
}

/** Сортировка по подписи для предсказуемого порядка в сетке и поиске. */
function sortByLabel(a: CategoryIconOption, b: CategoryIconOption): number {
  return a.label.localeCompare(b.label, undefined, { sensitivity: 'base' });
}

const CATEGORY_ICON_OPTIONS_RAW: CategoryIconOption[] = [
  { value: 'account_balance', label: 'Bank' },
  { value: 'account_balance_wallet', label: 'Wallet' },
  { value: 'apartment', label: 'Apartment' },
  { value: 'attach_money', label: 'Cash' },
  { value: 'bakery_dining', label: 'Bakery' },
  { value: 'beach_access', label: 'Beach & travel' },
  { value: 'bolt', label: 'Electricity' },
  { value: 'business_center', label: 'Business' },
  { value: 'cake', label: 'Cake & desserts' },
  { value: 'card_giftcard', label: 'Gifts' },
  { value: 'category', label: 'General' },
  { value: 'celebration', label: 'Events' },
  { value: 'checkroom', label: 'Clothing' },
  { value: 'child_care', label: 'Kids' },
  { value: 'cleaning_services', label: 'Cleaning' },
  { value: 'coffee', label: 'Coffee' },
  { value: 'computer', label: 'Computer' },
  { value: 'credit_card', label: 'Card payments' },
  { value: 'currency_exchange', label: 'Exchange' },
  { value: 'delivery_dining', label: 'Delivery food' },
  { value: 'directions_car', label: 'Car' },
  { value: 'directions_bus', label: 'Bus' },
  { value: 'dry_cleaning', label: 'Laundry' },
  { value: 'egg_alt', label: 'Groceries' },
  { value: 'emoji_events', label: 'Hobbies' },
  { value: 'engineering', label: 'Repairs' },
  { value: 'ev_station', label: 'EV charging' },
  { value: 'fastfood', label: 'Fast food' },
  { value: 'fitness_center', label: 'Gym' },
  { value: 'flight', label: 'Flights' },
  { value: 'home', label: 'Home' },
  { value: 'hotel', label: 'Hotel' },
  { value: 'inventory_2', label: 'Other' },
  { value: 'laptop_mac', label: 'Laptop' },
  { value: 'local_bar', label: 'Bar' },
  { value: 'local_cafe', label: 'Cafe' },
  { value: 'local_gas_station', label: 'Fuel' },
  { value: 'local_hospital', label: 'Health' },
  { value: 'local_parking', label: 'Parking' },
  { value: 'local_pizza', label: 'Pizza' },
  { value: 'local_taxi', label: 'Taxi' },
  { value: 'luggage', label: 'Luggage' },
  { value: 'medical_services', label: 'Clinic' },
  { value: 'medication', label: 'Pharmacy' },
  { value: 'menu_book', label: 'Books' },
  { value: 'movie', label: 'Entertainment' },
  { value: 'music_note', label: 'Music' },
  { value: 'payments', label: 'Payments' },
  { value: 'pets', label: 'Pets' },
  { value: 'phone_iphone', label: 'Phone' },
  { value: 'pool', label: 'Pool & sport' },
  { value: 'receipt', label: 'Receipts' },
  { value: 'restaurant', label: 'Restaurant' },
  { value: 'savings', label: 'Savings' },
  { value: 'school', label: 'Education' },
  { value: 'science', label: 'Science' },
  { value: 'self_improvement', label: 'Wellness' },
  { value: 'shopping_bag', label: 'Shopping bag' },
  { value: 'shopping_cart', label: 'Shopping' },
  { value: 'spa', label: 'Spa' },
  { value: 'sports_esports', label: 'Games' },
  { value: 'subscriptions', label: 'Subscriptions' },
  { value: 'train', label: 'Train' },
  { value: 'two_wheeler', label: 'Scooter' },
  { value: 'volunteer_activism', label: 'Charity' },
  { value: 'water_drop', label: 'Water' },
  { value: 'weekend', label: 'Leisure' },
  { value: 'work', label: 'Work' },
  { value: 'workspace_premium', label: 'Courses' },
  // —— дополнительные Material Icons (подпись для поиска и подсказки) ——
  { value: 'add_shopping_cart', label: 'Add to cart' },
  { value: 'airplane_ticket', label: 'Plane ticket' },
  { value: 'anchor', label: 'Anchor' },
  { value: 'architecture', label: 'Architecture' },
  { value: 'article', label: 'Article' },
  { value: 'assignment', label: 'Tasks' },
  { value: 'atm', label: 'ATM' },
  { value: 'baby_changing_station', label: 'Baby' },
  { value: 'bed', label: 'Bed & furniture' },
  { value: 'blender', label: 'Blender' },
  { value: 'book', label: 'Book' },
  { value: 'brush', label: 'Art & paint' },
  { value: 'bug_report', label: 'Software' },
  { value: 'build', label: 'Tools' },
  { value: 'bungalow', label: 'House' },
  { value: 'bus_alert', label: 'Bus alert' },
  { value: 'cabin', label: 'Cabin' },
  { value: 'calendar_month', label: 'Calendar' },
  { value: 'call', label: 'Calls' },
  { value: 'car_rental', label: 'Car rental' },
  { value: 'castle', label: 'Castle' },
  { value: 'chair_alt', label: 'Furniture' },
  { value: 'chat', label: 'Chat' },
  { value: 'church', label: 'Church' },
  { value: 'cloud', label: 'Cloud' },
  { value: 'coffee_maker', label: 'Coffee maker' },
  { value: 'color_lens', label: 'Color & lens' },
  { value: 'construction', label: 'Construction' },
  { value: 'cookie', label: 'Cookie' },
  { value: 'cottage', label: 'Cottage' },
  { value: 'deck', label: 'Deck' },
  { value: 'diamond', label: 'Jewelry' },
  { value: 'directions_boat', label: 'Boat' },
  { value: 'directions_subway', label: 'Subway' },
  { value: 'dns', label: 'DNS & web' },
  { value: 'dock', label: 'Dock' },
  { value: 'domain', label: 'Domain' },
  { value: 'downhill_skiing', label: 'Skiing' },
  { value: 'drafts', label: 'Drafts' },
  { value: 'eco', label: 'Eco' },
  { value: 'elderly', label: 'Elder care' },
  { value: 'electric_bolt', label: 'Power' },
  { value: 'emoji_food_beverage', label: 'Food & drink' },
  { value: 'energy_savings_leaf', label: 'Green energy' },
  { value: 'escalator_warning', label: 'Escalator' },
  { value: 'event_seat', label: 'Event seat' },
  { value: 'face', label: 'Face' },
  { value: 'factory', label: 'Factory' },
  { value: 'family_restroom', label: 'Family' },
  { value: 'favorite', label: 'Favorite' },
  { value: 'festival', label: 'Festival' },
  { value: 'filter_hdr', label: 'HDR & scenery' },
  { value: 'fire_hydrant', label: 'Utilities' },
  { value: 'flatware', label: 'Dining' },
  { value: 'flood', label: 'Flood' },
  { value: 'forest', label: 'Forest' },
  { value: 'forklift', label: 'Forklift' },
  { value: 'foundation', label: 'Foundation' },
  { value: 'free_breakfast', label: 'Breakfast' },
  { value: 'garage', label: 'Garage' },
  { value: 'gas_meter', label: 'Gas meter' },
  { value: 'gavel', label: 'Legal' },
  { value: 'golf_course', label: 'Golf' },
  { value: 'grass', label: 'Garden' },
  { value: 'group', label: 'Group' },
  { value: 'hail', label: 'Hail' },
  { value: 'handyman', label: 'Handyman' },
  { value: 'headphones', label: 'Headphones' },
  { value: 'hiking', label: 'Hiking' },
  { value: 'holiday_village', label: 'Holiday village' },
  { value: 'hot_tub', label: 'Hot tub' },
  { value: 'ice_skating', label: 'Ice skating' },
  { value: 'icecream', label: 'Ice cream' },
  { value: 'insights', label: 'Insights' },
  { value: 'iron', label: 'Ironing' },
  { value: 'keyboard', label: 'Keyboard' },
  { value: 'landscape', label: 'Landscape' },
  { value: 'leaderboard', label: 'Leaderboard' },
  { value: 'lightbulb', label: 'Ideas' },
  { value: 'local_atm', label: 'Local ATM' },
  { value: 'local_fire_department', label: 'Fire dept' },
  { value: 'local_florist', label: 'Florist' },
  { value: 'local_library', label: 'Library' },
  { value: 'local_mall', label: 'Mall' },
  { value: 'local_movies', label: 'Movies' },
  { value: 'local_phone', label: 'Phone booth' },
  { value: 'local_see', label: 'Sightseeing' },
  { value: 'local_shipping', label: 'Shipping' },
  { value: 'lock', label: 'Lock' },
  { value: 'mail', label: 'Mail' },
  { value: 'maps_home_work', label: 'Commute' },
  { value: 'meeting_room', label: 'Meeting room' },
  { value: 'military_tech', label: 'Defense' },
  { value: 'monitor', label: 'Monitor' },
  { value: 'motorcycle', label: 'Motorcycle' },
  { value: 'mouse', label: 'Mouse' },
  { value: 'museum', label: 'Museum' },
  { value: 'music_video', label: 'Music video' },
  { value: 'nature_people', label: 'Nature' },
  { value: 'night_shelter', label: 'Shelter' },
  { value: 'note_add', label: 'Notes' },
  { value: 'oil_barrel', label: 'Oil barrel' },
  { value: 'outdoor_grill', label: 'Grill' },
  { value: 'palette', label: 'Palette' },
  { value: 'panorama', label: 'Panorama' },
  { value: 'park', label: 'Park' },
  { value: 'percent', label: 'Percent' },
  { value: 'personal_injury', label: 'Injury' },
  { value: 'pest_control', label: 'Pest control' },
  { value: 'piano', label: 'Piano' },
  { value: 'pivot_table_chart', label: 'Pivot chart' },
  { value: 'plumbing', label: 'Plumbing' },
  { value: 'point_of_sale', label: 'POS' },
  { value: 'polyline', label: 'Route' },
  { value: 'precision_manufacturing', label: 'Manufacturing' },
  { value: 'propane', label: 'Propane' },
  { value: 'psychology', label: 'Therapy' },
  { value: 'public', label: 'Public' },
  { value: 'radar', label: 'Radar' },
  { value: 'radio', label: 'Radio' },
  { value: 'railway_alert', label: 'Railway' },
  { value: 'receipt_long', label: 'Long receipt' },
  { value: 'redeem', label: 'Redeem' },
  { value: 'rice_bowl', label: 'Rice bowl' },
  { value: 'roller_skating', label: 'Roller skate' },
  { value: 'router', label: 'Router' },
  { value: 'rowing', label: 'Rowing' },
  { value: 'rv_hookup', label: 'RV' },
  { value: 'satellite_alt', label: 'Satellite' },
  { value: 'scanner', label: 'Scanner' },
  { value: 'schema', label: 'Schema' },
  { value: 'scuba_diving', label: 'Diving' },
  { value: 'sentiment_satisfied', label: 'Happy' },
  { value: 'settings', label: 'Settings' },
  { value: 'shield', label: 'Shield' },
  { value: 'shop', label: 'Shop' },
  { value: 'shopping_basket', label: 'Basket' },
  { value: 'sick', label: 'Sick' },
  { value: 'sign_language', label: 'Sign language' },
  { value: 'skateboarding', label: 'Skateboard' },
  { value: 'sledding', label: 'Sled' },
  { value: 'snowboarding', label: 'Snowboard' },
  { value: 'snowmobile', label: 'Snowmobile' },
  { value: 'soap', label: 'Soap' },
  { value: 'solar_power', label: 'Solar' },
  { value: 'speaker', label: 'Speaker' },
  { value: 'speed', label: 'Speed' },
  { value: 'sports_bar', label: 'Sports bar' },
  { value: 'sports_golf', label: 'Golf sport' },
  { value: 'square_foot', label: 'Real estate' },
  { value: 'stairs', label: 'Stairs' },
  { value: 'storefront', label: 'Storefront' },
  { value: 'storm', label: 'Storm' },
  { value: 'surfing', label: 'Surf' },
  { value: 'synagogue', label: 'Synagogue' },
  { value: 'table_restaurant', label: 'Restaurant table' },
  { value: 'takeout_dining', label: 'Takeout' },
  { value: 'tapas', label: 'Tapas' },
  { value: 'theater_comedy', label: 'Theater' },
  { value: 'thermostat', label: 'Thermostat' },
  { value: 'thumb_up', label: 'Like' },
  { value: 'thunderstorm', label: 'Thunder' },
  { value: 'timelapse', label: 'Timelapse' },
  { value: 'tire_repair', label: 'Tire' },
  { value: 'toys', label: 'Toys' },
  { value: 'traffic', label: 'Traffic' },
  { value: 'tram', label: 'Tram' },
  { value: 'travel_explore', label: 'Explore' },
  { value: 'tsunami', label: 'Tsunami' },
  { value: 'tune', label: 'Tune' },
  { value: 'tv', label: 'TV' },
  { value: 'umbrella', label: 'Umbrella' },
  { value: 'videogame_asset', label: 'Gaming' },
  { value: 'villa', label: 'Villa' },
  { value: 'visibility', label: 'Visibility' },
  { value: 'volcano', label: 'Volcano' },
  { value: 'vpn_key', label: 'VPN' },
  { value: 'warehouse', label: 'Warehouse' },
  { value: 'wash', label: 'Wash' },
  { value: 'water', label: 'Water' },
  { value: 'waves', label: 'Waves' },
  { value: 'wc', label: 'WC' },
  { value: 'wheelchair_pickup', label: 'Accessibility' },
  { value: 'wifi', label: 'Wi‑Fi' },
  { value: 'wine_bar', label: 'Wine bar' },
  { value: 'woman', label: 'Woman' },
];

export const CATEGORY_ICON_OPTIONS: CategoryIconOption[] = [...CATEGORY_ICON_OPTIONS_RAW].sort(
  sortByLabel,
);

/** Все допустимые имена иконок — синхронизируйте с `backend/.../valid-icons.const.ts`. */
export const CATEGORY_ICON_VALUES_ALL: readonly string[] = Array.from(
  new Set(CATEGORY_ICON_OPTIONS.map((o) => o.value)),
);

/** Возвращает имя иконки для отображения; при пустом или неизвестном — default. */
export function getCategoryIconName(icon: string | null | undefined): string {
  if (icon == null || icon === '') return DEFAULT_CATEGORY_ICON;
  return icon;
}
