import { Transaction } from '../types';

export const transactions: Transaction[] = [
  {
    id: 0,
    title: 'GTR 5',
    category: 'Auto',
    amount: 1000,
    date: '2024-01-01',
    type: 'Expenses',
    paymentMethod: 'Cash',
    cardId: 0,
    receipt: 'R8-12-01',
    status: 'Pending',
    transactionType: 'Debit',
    userId: 0,
  },
  {
    id: 1,
    title: 'Groceries',
    category: 'Food',
    amount: 210,
    date: '2024-01-08',
    type: 'Expenses',
    paymentMethod: 'Card',
    cardId: 0,
    receipt: 'R8-12-02',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 0,
  },
  {
    id: 2,
    title: 'Coffee',
    category: 'Food',
    amount: 5,
    date: '2024-01-10',
    type: 'Expenses',
    paymentMethod: 'Cash',
    cardId: 0,
    receipt: 'R8-12-03',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 0,
  },
  {
    id: 3,
    title: 'Cinema',
    category: 'Entertainment',
    amount: 12,
    date: '2024-01-12',
    type: 'Expenses',
    paymentMethod: 'Card',
    cardId: 0,
    receipt: 'R8-12-04',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 0,
  },
  {
    id: 4,
    title: 'Book',
    category: 'Education',
    amount: 25,
    date: '2024-01-15',
    type: 'Expenses',
    paymentMethod: 'Card',
    cardId: 0,
    receipt: 'R8-12-05',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 0,
  },
  {
    id: 5,
    title: 'Taxi',
    category: 'Transport',
    amount: 18,
    date: '2024-01-20',
    type: 'Expenses',
    paymentMethod: 'Cash',
    cardId: 0,
    receipt: 'R8-12-06',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 0,
  },
  {
    id: 6,
    title: 'Restaurant',
    category: 'Food',
    amount: 85,
    date: '2024-02-01',
    type: 'Expenses',
    paymentMethod: 'Card',
    cardId: 0,
    receipt: 'R8-12-07',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 0,
  },
  {
    id: 7,
    title: 'Gym',
    category: 'Health',
    amount: 40,
    date: '2024-02-05',
    type: 'Expenses',
    paymentMethod: 'Card',
    cardId: 0,
    receipt: 'R8-12-08',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 0,
  },

  {
    id: 8,
    title: 'Polo Shirt',
    category: 'Clothes',
    amount: 546,
    date: '2023-06-12',
    type: 'Expenses',
    paymentMethod: 'Card',
    cardId: 1,
    receipt: 'R7-91-01',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 1,
  },
  {
    id: 9,
    title: 'Salary',
    category: 'Job',
    amount: 3200,
    date: '2024-03-05',
    type: 'Revenue',
    paymentMethod: 'Bank Transfer',
    cardId: 1,
    receipt: 'SAL-20240305',
    status: 'Completed',
    transactionType: 'Credit',
    userId: 1,
  },
  {
    id: 10,
    title: 'Electricity Bill',
    category: 'Utilities',
    amount: 120,
    date: '2024-03-07',
    type: 'Expenses',
    paymentMethod: 'Card',
    cardId: 1,
    receipt: 'BILL-20240307',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 1,
  },
  {
    id: 11,
    title: 'Internet',
    category: 'Utilities',
    amount: 30,
    date: '2024-03-10',
    type: 'Expenses',
    paymentMethod: 'Card',
    cardId: 1,
    receipt: 'BILL-20240310',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 1,
  },
  {
    id: 12,
    title: 'Gift',
    category: 'Gifts',
    amount: 60,
    date: '2024-03-12',
    type: 'Expenses',
    paymentMethod: 'Card',
    cardId: 1,
    receipt: 'GFT-20240312',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 1,
  },
  {
    id: 13,
    title: 'Petrol',
    category: 'Auto',
    amount: 55,
    date: '2024-03-20',
    type: 'Expenses',
    paymentMethod: 'Card',
    cardId: 1,
    receipt: 'PET-20240320',
    status: 'Pending',
    transactionType: 'Debit',
    userId: 1,
  },
  {
    id: 14,
    title: 'Freelance',
    category: 'Job',
    amount: 450,
    date: '2024-04-01',
    type: 'Revenue',
    paymentMethod: 'Bank Transfer',
    cardId: 1,
    receipt: 'FRL-20240401',
    status: 'Completed',
    transactionType: 'Credit',
    userId: 1,
  },

  {
    id: 15,
    title: 'Taxi',
    category: 'Transport',
    amount: 123,
    date: '2024-03-02',
    type: 'Expenses',
    paymentMethod: 'Cash',
    cardId: 2,
    receipt: 'TAX-20240302',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 2,
  },
  {
    id: 16,
    title: 'Netflix Subscription',
    category: 'Entertainment',
    amount: 15,
    date: '2024-03-15',
    type: 'Expenses',
    paymentMethod: 'Card',
    cardId: 2,
    receipt: 'SUB-20240315',
    status: 'Pending',
    transactionType: 'Debit',
    userId: 2,
  },
  {
    id: 17,
    title: 'Groceries',
    category: 'Food',
    amount: 95,
    date: '2024-03-18',
    type: 'Expenses',
    paymentMethod: 'Card',
    cardId: 2,
    receipt: 'GRC-20240318',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 2,
  },
  {
    id: 18,
    title: 'Phone',
    category: 'Utilities',
    amount: 20,
    date: '2024-03-21',
    type: 'Expenses',
    paymentMethod: 'Card',
    cardId: 2,
    receipt: 'PHN-20240321',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 2,
  },
  {
    id: 19,
    title: 'Coffee',
    category: 'Food',
    amount: 4,
    date: '2024-03-22',
    type: 'Expenses',
    paymentMethod: 'Cash',
    cardId: 2,
    receipt: 'CF-20240322',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 2,
  },
  {
    id: 20,
    title: 'Book',
    category: 'Education',
    amount: 18,
    date: '2024-04-02',
    type: 'Expenses',
    paymentMethod: 'Card',
    cardId: 2,
    receipt: 'BK-20240402',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 2,
  },

  {
    id: 21,
    title: 'Stock Dividend',
    category: 'Investment',
    amount: 450,
    date: '2024-03-20',
    type: 'Revenue',
    paymentMethod: 'Bank Transfer',
    cardId: 3,
    receipt: 'DIV-20240320',
    status: 'Completed',
    transactionType: 'Credit',
    userId: 3,
  },
  {
    id: 22,
    title: 'Broker Fee',
    category: 'Investment',
    amount: 12,
    date: '2024-03-22',
    type: 'Expenses',
    paymentMethod: 'Card',
    cardId: 3,
    receipt: 'BRK-20240322',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 3,
  },
  {
    id: 23,
    title: 'ETF Purchase',
    category: 'Investment',
    amount: 1200,
    date: '2024-04-05',
    type: 'Expenses',
    paymentMethod: 'Card',
    cardId: 3,
    receipt: 'ETF-20240405',
    status: 'Pending',
    transactionType: 'Debit',
    userId: 3,
  },
  {
    id: 24,
    title: 'Dividend Reinvest',
    category: 'Investment',
    amount: 50,
    date: '2024-04-15',
    type: 'Revenue',
    paymentMethod: 'Bank Transfer',
    cardId: 3,
    receipt: 'DIVR-20240415',
    status: 'Completed',
    transactionType: 'Credit',
    userId: 3,
  },

  {
    id: 25,
    title: 'Loan Payment',
    category: 'Loan',
    amount: 600,
    date: '2024-03-22',
    type: 'Expenses',
    paymentMethod: 'Bank Transfer',
    cardId: 5,
    receipt: 'LN-20240322',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 4,
  },
  {
    id: 26,
    title: 'Loan Interest',
    category: 'Loan',
    amount: 45,
    date: '2024-04-22',
    type: 'Expenses',
    paymentMethod: 'Bank Transfer',
    cardId: 5,
    receipt: 'LNI-20240422',
    status: 'Pending',
    transactionType: 'Debit',
    userId: 4,
  },

  {
    id: 27,
    title: 'Promo Cashback',
    category: 'Rewards',
    amount: 10,
    date: '2024-04-01',
    type: 'Revenue',
    paymentMethod: 'Card',
    cardId: 4,
    receipt: 'CB-20240401',
    status: 'Completed',
    transactionType: 'Credit',
    userId: 5,
  },
  {
    id: 28,
    title: 'Empty Card Test 1',
    category: 'Misc',
    amount: 0,
    date: '2024-04-02',
    type: 'Expenses',
    paymentMethod: 'Card',
    cardId: 4,
    receipt: 'TST-20240402',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 5,
  },
  {
    id: 29,
    title: 'Empty Card Test 2',
    category: 'Misc',
    amount: 0,
    date: '2024-04-03',
    type: 'Expenses',
    paymentMethod: 'Card',
    cardId: 4,
    receipt: 'TST-20240403',
    status: 'Completed',
    transactionType: 'Debit',
    userId: 5,
  },
];

export const tabs = ['All', 'Expenses', 'Revenue'];
