export enum RoutePaths {
  LOGIN = 'login',
  SIGNUP = 'signup',
  DASHBOARD = 'dashboard',
  NOT_FOUND = '404',
  SETTINGS = 'settings',
  TRANSACTIONS = 'transactions',
  STATISTICS = 'statistics',
  EXPENSES = 'expenses',
  GOALS = 'goals',
  SUBSCRIPTIONS = 'subscriptions',
  BAlANCES = 'balances',
  BALANCE_DETAILS = 'balance-details',
  EXPENSES_DETAILS = 'expenses-details',
}
